name: .NET Core CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages  
  NUGET_HTTP_CACHE_PATH: ${{ github.workspace }}/.nuget/http-cache    
  DOTNET_VERSION: '10.0.x'
  VERLITE_VERSION: '"2.6.0"'

jobs:
  build:
    runs-on: ubuntu-24.04
    #if: github.event.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v4 # Checks out your repository

    - name: Setup .NET
      uses: actions/setup-dotnet@v4 # Sets up the .NET SDK
      with: |
        echo github.event.ref
        echo github.event.ref_name
        dotnet-version: ${{ env.DOTNET_VERSION }} # Specify your .NET version

    - name: Restore dependencies
      run: dotnet restore # Restores NuGet packages

    - name: install verlite for semantic versioning
      run: |
        dotnet tool install --global Verlite.CLI --version ${{ env.VERLITE_VERSION }}
        echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
        verlite --auto-fetch

    - name: Build
      run: dotnet build --no-restore --configuration Release # Compiles the app

    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal
