name: .NET Core CI

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+' 
  pull_request:
    branches: [ "main" ]

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages  
  NUGET_HTTP_CACHE_PATH: ${{ github.workspace }}/.nuget/http-cache    
  DOTNET_VERSION: '10.0.x'
  VERLITE_VERSION: '"2.6.0"'

jobs:
  check-branch:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: vars
        run: |
          # Finds remote branches containing the tag, strips 'origin/', and takes the first match
          BRANCH=$(git branch -r --contains ${{ github.ref }} | head -n 1 | sed 's/.*origin\///')
          echo "branch=$BRANCH" >> $GITHUB_OUTPUT

      - name: Use branch name
        run: echo "Running on branch ${{ steps.vars.outputs.branch }}"

  build-and-test:
    runs-on: self-hosted
    needs: check-branch
    if: needs.check-branch.vars.outputs.vars.branch == 'main'    
    steps:  
      - name: Setup .NET
        uses: actions/setup-dotnet@v4 # Sets up the .NET SDK
        with: 
          dotnet-version: ${{ env.DOTNET_VERSION }} # Specify your .NET version

      - name: Restore dependencies
        run: dotnet restore # Restores NuGet packages

      - name: install verlite for semantic versioning
        run: |
          dotnet tool install --global Verlite.CLI --version ${{ env.VERLITE_VERSION }}
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH
          verlite --auto-fetch

      - name: Build
        run: dotnet build --no-restore --configuration Release # Compiles the app

      - name: Test
        run: dotnet test --no-build --configuration Release --verbosity normal        

  # check-tag:
  #   runs-on: ubuntu-24.04
  #   outputs:
  #     is_version: ${{ steps.check.outputs.is_version }}
  #   steps:
  #     - id: check
  #       run: |
  #         if [[ "${{ github.ref_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
  #           echo "is_version=true" >> $GITHUB_OUTPUT
  #         fi

  # build:
  #   runs-on: ubuntu-24.04
  #   needs: check-tag
  #   if: needs.check-tag.outputs.is_version == 'true'

  #   steps:
  #   - uses: actions/checkout@v4 # Checks out your repository


